name: Generate Calendar

on:
  schedule:
    - cron: '0 0-23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fetch schedules
        run: node index.js

      - name: Generate calendar
        run: node calendar.js

      - name: Commit iCal
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pshs-athletics.ics data/combined.json
          git commit -m "Update iCal and schedule" || echo "No changes"
          git push