# .github/workflows/deploy.yml
name: Update Schedule & Calendar

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes (or use your preferred time)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run index.js (fetch and build schedule JSON)
        run: node index.js

      - name: Run calendar.js (generate .ics file)
        run: node calendar.js

      - name: Copy static site files
        run: |
          mkdir -p dist
          cp index.html index.js dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist