name: Weekly Commit Squash

on:
  schedule:
    - cron: '30 4 * * 0'  # Sundays at 4:30 AM UTC (11:30 PM ET Saturday)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  squash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important! gets full history

      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Squash all auto-commits into one
        run: |
          LAST_REAL_COMMIT=$(git log --grep='^🔄 Auto-update schedule JSONs' --invert-grep --pretty=format:%H | head -n 1)

          if [ -z "$LAST_REAL_COMMIT" ]; then
            echo "No non-auto commits found — skipping squash."
            exit 0
          fi

          git reset --soft $LAST_REAL_COMMIT
          git commit -m "📦 Weekly schedule data summary"
          git push --force
